name: CI/CD Build & Deploy Flutter Web to Firebase Hosting

on: 
  push:
    branches: 
      - main 

jobs: 
  Deployment:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5' 

      - name: Delete main.dart
        run: rm -f lib/main.dart

      - name: Create new main.dart
        run: |
          cat << 'EOF' > lib/main.dart
          
          EOF

      - name: Delete firebase_options.dart
        run: rm -f lib/firebase_options.dart

      - name: Create new main.dart
        run: |
          mkdir -p lib
          cat <<EOF > lib/firebase_options.dart
          
          EOF

      - name: Delete pubspec.yaml
        run: rm -f pubspec.yaml

      - name: Create new pubspec.yaml
        run: |
          cat << 'EOF' > pubspec.yaml
          name: traderview
          description: "A new Flutter project."
          publish_to: 'none'
          version: 1.0.0+1

          environment:
            sdk: ^3.5.4

          dependencies:
            flutter:
              sdk: flutter

            flutter_web_plugins:
              sdk: flutter

            cupertino_icons: ^1.0.8
            url_launcher: ^6.0.20
            go_router: ^15.1.1
            firebase_core: ^3.10.1
            cloud_firestore: ^5.6.0
            font_awesome_flutter: 10.8.0
            provider: ^6.1.5
            firebase_auth: ^5.4.2
            intl: ^0.19.0

            flutter_localizations:
              sdk: flutter

          dev_dependencies:
            flutter_test:
              sdk: flutter

            flutter_lints: ^5.0.0

          flutter:
            uses-material-design: true

            assets:
              - assets/
              - assets/images/
          EOF
    
      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter commands
        run: flutter analyze

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live